version: "3.8"

services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: billing_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: client_billing_db
      MYSQL_USER: billing_user
      MYSQL_PASSWORD: billing_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - billing_network

  # Backend Server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: billing_server
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=client_billing_db
      - DB_USER=billing_user
      - DB_PASSWORD=billing_password
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - billing_network
    volumes:
      - ./server:/app
      - /app/node_modules

  # Frontend Client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: billing_client
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - billing_network

volumes:
  mysql_data:

networks:
  billing_network:
    driver: bridge
