import React, { useState } from "react";

const ClientForm = ({ onSubmit, initialData = null }) => {
  const [formData, setFormData] = useState({
    name: initialData?.name || "",
    code: initialData?.code || "",
    phone: initialData?.phone || "",
  });

  const handleChange = (e) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value,
    });
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    if (!formData.name || !formData.phone) {
      alert("Please fill in name and phone number");
      return;
    }

    // If no code provided, it will be auto-generated by the backend
    const submitData = {
      name: formData.name.trim(),
      phone: formData.phone.trim(),
    };

    // Only include code if it's provided (for updates)
    if (formData.code.trim()) {
      submitData.code = formData.code.trim();
    }

    onSubmit(submitData);
    if (!initialData) {
      setFormData({ name: "", code: "", phone: "" });
    }
  };

  return (
    <form onSubmit={handleSubmit}>
      <div className="form-group">
        <label htmlFor="name">Name:</label>
        <input
          type="text"
          id="name"
          name="name"
          value={formData.name}
          onChange={handleChange}
          required
        />
      </div>

      <div className="form-group">
        <label htmlFor="code">
          Code:{" "}
          <small style={{ color: "#666" }}>
            (optional - will be auto-generated)
          </small>
        </label>
        <input
          type="text"
          id="code"
          name="code"
          value={formData.code}
          onChange={handleChange}
          placeholder="Leave empty for auto-generation"
        />
      </div>

      <div className="form-group">
        <label htmlFor="phone">Phone:</label>
        <input
          type="tel"
          id="phone"
          name="phone"
          value={formData.phone}
          onChange={handleChange}
          required
        />
      </div>

      <button type="submit" className="btn btn-primary">
        {initialData ? "Update Client" : "Add Client"}
      </button>
    </form>
  );
};

export default ClientForm;
